
[package]
name = "secret-notes-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["staking"] }
cosmwasm-storage = "1.0.0"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = "1.0.31"
secret-toolkit = { version = "0.7.0", default-features = false, features = ["storage", "serialization"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"